repos:
  - repo: local
    hooks:
      - id: cargo-fmt     # formatting
        name: cargo fmt
        entry: cargo fmt --all --
        language: system
        types: [rust]
      - id: cargo-clippy  # linting
        name: cargo clippy
        entry: cargo clippy --locked --all-targets -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
