{{- if and .Values.tokenSecret.create (not .Values.discord.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tokenSecret.name }}
  labels:
    {{- include "checkipbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  DISCORD_TOKEN: {{ required "discord.token is required when not using discord.existingSecret" .Values.discord.token | quote }}
{{- end }}
