name: Lint

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal --component rustfmt,clippy

      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2

      - name: Format check (cargo fmt)
        run: cargo fmt --all --check

      - name: Lint (cargo clippy)
        run: cargo clippy --locked --all-targets -- -D warnings
